# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            The Budding Programmer
tagline:          'A Jekyll theme'
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my site! Here you will find all of the projects I've completed starting with
  my class project at Seattle University to personal projects. Also, more information about me! Thanks!
url:              "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:         ""  # the subpath of your site, e.g. /blog

author:
  name:           'Alicia Garcia'
  linkedin_username: aligarcial
  url:            https://www.linkedin.com/in/aligarcial/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gaaliciA1990/gaaliciA1990.github.io

plugins:
  - jekyll-feed
